apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubik
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubik
  template:
    metadata:
      labels:
        app: kubik
    spec:
      containers:
      - name: kubik
        image: proz/kubik