application: scripts-to-words
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: (/upload)|(/tokenize)|(/words)
  login: required
  script: _go_app

- url: /.*
  script: _go_app