apiVersion: v1
kind: Pod
metadata:
  name: kubik-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: proz/kubik
    name: kubik
    ports:
    - containerPort: 8080
      protocol: TCP